apiVersion: v2
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 1.x.x
description: A Helm chart for MOSIP OIDC UI module
home: https://mosip.io
keywords:
- mosip
- mock-relying-party-ui
maintainers:
- email: info@mosip.io
  name: MOSIP
name: mock-relying-party-ui
type: application
version: 0.9.2
