apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ template "vault-init.fullname" . }}-sa-role
  labels:
    app.kubernetes.io/name: {{ include "vault-init.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - pods/exec
  - secrets
  verbs:
  - create
  - get
  - list
