apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ template "vault-init.fullname" . }}-sa-rolebinding
  labels:
    app.kubernetes.io/name: {{ include "vault-init.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ template "vault-init.fullname" . }}-sa-role
subjects:
- kind: ServiceAccount
  name: {{ include "vault-init.serviceAccountName" . }}
