apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-exec-role-binding
subjects:
- kind: ServiceAccount
  name: {{ include "vault-init.serviceAccountName" . }}
roleRef:
  kind: Role
  name: pod-exec-role
  apiGroup: rbac.authorization.k8s.io

